Repository WordPress/create-block-theme, pull requests merged in 2023-02, with the labels that each got.

#193 Add placeholder screenshot to boilerplate theme
  assets/boilerplate/screenshot.png
Labels: enhancement

#194 Refactor: Add Google Fonts section from vanilla JS to React app
  admin/class-manage-fonts.php
  admin/js/google-fonts.js
  css/google-fonts.css
  src/google-fonts/font-variant.js
  src/google-fonts/index.js
  src/google-fonts/utils.js
  src/index.js
  src/manage-fonts/font-face.js
  src/manage-fonts/font-family.js
  src/manage-fonts/index.js
Labels: enhancement

#208 check for DISALLOW_FILE_EDIT and simplify permission check logic
  admin/class-manage-fonts.php
Labels: bug, enhancement

#214 Add spinner while google fonts load instead of showing a blank page
  src/google-fonts/index.js
Labels: enhancement

#196 Add: code linting scripts
  .browserslistrc
  .editorconfig
  .eslintignore
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .phpcs.xml.dist
  .prettierignore
  .prettierrc.js
  .stylelintignore
  .stylelintrc.json
  admin/index.php
  babel.config.js
  composer.json
  composer.lock
  includes/index.php
  index.php
  package-lock.json
  package.json
Labels: enhancement

#220 Update main readme and add supporting docs
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#226 Cleanup Manage Theme Fonts UI
  admin/class-manage-fonts.php
  src/fonts-context.js
  src/manage-fonts/font-face.js
  src/manage-fonts/font-family.js
  src/manage-fonts/manage-fonts.css
Labels: enhancement

#213 Bundle template images into theme assets and make their urls relative
  admin/class-create-block-theme-admin.php
Labels: enhancement

#224 Add: input for theme tags
  admin/class-create-block-theme-admin.php
  admin/css/form.css
  admin/js/form-script.js
  admin/theme_tags.php
Labels: enhancement
