Repository WordPress/create-block-theme, pull requests merged in 2023-05, with the labels that each got.

#298 Automatically add font license info for Google fonts
  admin/class-manage-fonts.php
  composer.json
  composer.lock
  phpcs.xml.dist
  src/google-fonts/index.js
Labels: enhancement

#359 Improve handling of font license errors
  admin/class-manage-fonts.php
  src/google-fonts/index.js
Labels: bug, [Feature] Font Management

#367 Automatically add font license info for local fonts
  src/google-fonts/index.js
  src/local-fonts/upload-font-form.js
Labels: [Feature] Font Management

#374 Escape special characters to avoid syntax errors
  admin/create-theme/theme-patterns.php
Labels: bug

#380 Add image credits input
  admin/class-create-theme.php
  admin/create-theme/theme-form.php
  admin/create-theme/theme-readme.php
  admin/create-theme/theme-tags.php
Labels: enhancement
