Repository WordPress/create-block-theme, pull requests merged in 2024-09, with the labels that each got.

#683 Update escaping function
  includes/create-theme/theme-locale.php
  includes/create-theme/theme-patterns.php
  tests/CbtThemeLocale/escapeAttribute.php
  tests/CbtThemeLocale/escapeString.php
  tests/CbtThemeLocale/escapeTextContent.php
  tests/CbtThemeLocale/escapeTextContentOfBlocks.php
  tests/test-theme-templates.php
Labels: bug

#712 Rename font assets when theme is saved and/or exported
  composer.lock
  includes/create-theme/theme-fonts.php
  includes/create-theme/theme-zip.php
  tests/test-theme-fonts.php
Labels: enhancement, [Feature] Font Management

#675 Try: Add synced patterns to theme on save
  includes/class-create-block-theme-api.php
  includes/create-theme/theme-patterns.php
  includes/create-theme/theme-templates.php
  src/editor-sidebar/save-panel.js
Labels: enhancement

#718 Remove "Categories: hidden" from default pattern header
  includes/create-theme/theme-patterns.php
  tests/test-theme-utils.php
Labels: enhancement

#713 Copy font assets to the local theme folder when creating a style variation
  includes/class-create-block-theme-api.php
  includes/create-theme/resolver_additions.php
  includes/create-theme/theme-fonts.php
  includes/create-theme/theme-json.php
  src/editor-sidebar/create-variation-panel.js
  src/resolvers.js
Labels: enhancement, [Feature] Font Management
