Repository WordPress/create-block-theme, pull requests merged in 2024-05, with the labels that each got.

#617 Update Node version to 20
  .github/workflows/deploy-to-dotorg.yml
  .github/workflows/release-new-version.yml
  .nvmrc
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: build tooling

#614 Add Repository Management section to contributing docs
  CONTRIBUTING.md
Labels: documentation

#611 Proposal: Use non-default port for wp-env
  .wp-env.json
Labels: enhancement, build tooling

#628 Add prefix to the names in the PHP global namespace.
  admin/class-create-theme.php
  admin/create-theme/cbt-zip-archive.php
  admin/create-theme/form-messages.php
  admin/create-theme/theme-create.php
  admin/create-theme/theme-fonts.php
  admin/create-theme/theme-form.php
  admin/create-theme/theme-json.php
  admin/create-theme/theme-media.php
  admin/create-theme/theme-patterns.php
  admin/create-theme/theme-readme.php
  admin/create-theme/theme-styles.php
  admin/create-theme/theme-tags.php
  admin/create-theme/theme-templates.php
  admin/create-theme/theme-utils.php
  admin/create-theme/theme-zip.php
  admin/resolver_additions.php
  admin/wp-org-theme-directory.php
  create-block-theme.php
  includes/class-create-block-theme-api.php
  includes/class-create-block-theme-loader.php
  includes/class-create-block-theme.php
  tests/CbtThemeReadme/addOrUpdateSection.php
  tests/CbtThemeReadme/base.php
  tests/CbtThemeReadme/create.php
  tests/CbtThemeReadme/filePath.php
  tests/CbtThemeReadme/getContent.php
  tests/CbtThemeReadme/update.php
  tests/test-theme-fonts.php
  tests/test-theme-media.php
  tests/test-theme-templates.php
  tests/test-theme-utils.php
Labels: enhancement

#636 Clean and complete the changelog
  readme.txt
Labels: documentation

#641 Fix template texts localizing/escaping
  admin/class-create-theme.php
  admin/create-theme/theme-locale.php
  admin/create-theme/theme-templates.php
  tests/CbtThemeLocale/base.php
  tests/CbtThemeLocale/escapeString.php
  tests/CbtThemeLocale/escapeTextContentOfBlocks.php
  tests/data/themes/test-theme-locale/style.css
  tests/data/themes/test-theme-locale/theme.json
  tests/test-theme-templates.php
Labels: bug
