Repository WordPress/create-block-theme, pull requests merged in 2024-04, with the labels that each got.

#541 Fix changelog creation script
  .wordpress-org/screenshot-1.jpg
  .wordpress-org/screenshot-2.jpg
  .wordpress-org/screenshot-3.jpg
  .wordpress-org/screenshot-4.jpg
  assets/screenshot-1.jpg
  assets/screenshot-2.jpg
  assets/screenshot-3.jpg
  assets/screenshot-4.jpg
  assets/screenshot-5.jpg
  update-version-and-changelog.js
Labels: bug, build tooling

#555 Update readme files with editor-specific steps and screenshot references
  README.md
  readme.txt
Labels: documentation

#580 Try to fix screenshots in readme.txt
  readme.txt
Labels: bug

#577 Code Quality: Remove `no-undef` eslint rule
  .eslintrc.json
  src/editor-sidebar/metadata-editor-modal.js
  src/editor-sidebar/save-panel.js
  src/fonts-context.js
  src/fonts-sidebar/index.js
  src/google-fonts/index.js
  src/manage-fonts/back-button.js
  src/manage-fonts/font-family.js
  src/manage-fonts/page-header.js
  src/utils.js
Labels: build tooling

#582 Fix error when exporting theme with no fonts
  admin/create-theme/theme-zip.php
Labels: bug

#595 Remove font management
  admin/class-manage-fonts.php
  admin/class-react-app.php
  admin/font-helpers.php
  admin/manage-fonts/font-form-messages.php
  admin/manage-fonts/fonts-page.php
  admin/manage-fonts/google-fonts-page.php
  admin/manage-fonts/local-fonts-page.php
  includes/class-create-block-theme.php
  package.json
  src/constants.js
  src/demo-text-input/axis-range-control.js
  src/demo-text-input/demo-text-input.css
  src/demo-text-input/demo.js
  src/demo-text-input/index.js
  src/demo-text-input/utils.js
  src/demo-text-input/variable-controls.js
  src/fonts-context.js
  src/fonts-page-layout/fonts-page-layout.css
  src/fonts-page-layout/index.js
  src/fonts-sidebar/fonts-sidebar.css
  src/fonts-sidebar/index.js
  src/google-fonts/font-variant.js
  src/google-fonts/google-fonts.css
  src/google-fonts/index.js
  src/index.js
  src/index.scss
  src/local-fonts/index.js
  src/local-fonts/local-fonts.css
  src/local-fonts/upload-font-form.js
  src/manage-fonts/back-button.js
  src/manage-fonts/confirm-delete-modal.js
  src/manage-fonts/font-face.js
  src/manage-fonts/font-family.js
  src/manage-fonts/help-modal.js
  src/manage-fonts/index.js
  src/manage-fonts/manage-fonts.css
  src/manage-fonts/page-header.js
  src/test/unit.js
  src/utils.js
Labels: enhancement

#593 Make sure code is being deployed to the directory only on Release PR Merge
  .github/workflows/deploy-to-dotorg.yml
Labels: bug

#594 Document the release process
  CONTRIBUTING.md
Labels: documentation

#601 Fix custom fonts assets path
  admin/create-theme/theme-zip.php
Labels: bug
